name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - main
    tags:
    - '*'
jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: install boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        $ErrorActionPreference = 'Stop'
        $Url = "https://boostorg.jfrog.io/artifactory/main/release/1.85.0/source/boost_1_85_0.7z"
         (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost_1_85_0.7z")
        7z.exe x "$env:TEMP\boost_1_85_0.7z"
        cd boost_1_85_0
        ECHO "---"
        DIR "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\"
        ECHO "---"
        DIR "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxliary"
        ECHO "---"
        DIR "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxliary\Build"
        ECHO "---"
        DIR "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\"
        ECHO "---"
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        ECHO "---"
        .\bootstrap.bat
        DIR
        .\b2.exe --help
#        New-Item -ItemType Directory -Force -Path D:\a\gha_install_boost\gha_install_boost\boost
#        Start-Process -FilePath .\b2.exe -ArgumentList "toolset=msvc link=static,shared address-model=64 -j2 --prefix=D:\a\gha_install_boost\gha_install_boost\boost install --with-container --with-filesystem --with-log --with-program_options --with-system --with-test" -NoNewWindow -Wait -RedirectStandardOutput D:\a\gha_install_boost\gha_install_boost\boost\boost_build_log.txt
#        .\b2.exe toolset=msvc link=static,shared address-model=64 -j2 --prefix=D:\a\gha_install_boost\gha_install_boost\boost install --with-container --with-filesystem --with-log --with-program_options --with-system --with-test > D:\a\gha_install_boost\gha_install_boost\boost\boost_build_log.txt
    - name: Output Boost Build Log
      if: always()
      shell: bash
      run: cat D:\a\gha_install_boost\gha_install_boost\boost\boost_build_log.txt
