name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - main
    tags:
    - '*'
jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: install boost
      shell: powershell
      run: |
        $ErrorActionPreference = 'Stop'
        pwd
        $Url = "https://boostorg.jfrog.io/artifactory/main/release/1.85.0/source/boost_1_85_0.7z"
         (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost_1_85_0.7z")
        7z.exe x "$env:TEMP\boost_1_85_0.7z"
        cd boost_1_85_0
        ECHO "---"
        & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        ECHO "---"
        .\bootstrap.bat
        ECHO "---"
        pwd
        ECHO "---"
        dir
        ECHO "---"
        & ".\b2.exe" --help
        ECHO "---"
